# Generated by Django 4.2 on 2026-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentmetadata_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmetadata',
            name='travel_outcome_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='travel_roi_rating',
            field=models.CharField(blank=True, choices=[('Negligible Impact', 'Negligible Impact'), ('Low Impact', 'Low Impact'), ('Moderate Benefit', 'Moderate Benefit'), ('High Strategic Impact', 'High Strategic Impact'), ('Critical National Benefit', 'Critical National Benefit')], max_length=50, null=True),
        ),
    ]
