# Generated by Django 4.2 on 2026-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='action',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Request Changes', 'Request Changes'), ('Comment', 'Comment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
