# Generated by Django 4.2 on 2026-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_delegation_id_alter_workflowstep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='digital_signature_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='signature_image',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='verification_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
